### ISSUE TITLE
Nuxt3.8以降でgenerateした結果をpreviewできない

### ISSUE THREAD

**Issue by dc7290** [microcmsio/nuxt-microcms-module#15]
> 先日公開された Nuxt3.8 環境で、target: 'server' の状態のまま generate を実行した際、生成されたデータを preview すると正常に表示が行われなくなりました（401が返ってくる状態）
> target: 'all' であれば、問題なく表示が行われます。

https://discord.com/channels/1029590791997358101/1166017823441690774

**Comment by Sinhalite** [comment]
以下のPRが3.8.2よりマージされて、修正されていることを確認したので、クローズします！
https://github.com/nuxt/nuxt/pull/24333
