### ISSUE TITLE
Ques: 本モジュールは今後もサポートされていきますか？

### ISSUE THREAD

**Issue by shinGangan** [microcmsio/nuxt-microcms-module#16]
### Context

メンテナーチーム様、いつもmicroCMSの開発ありがとうございます。
素晴らしい機能が多く助かっております。

私は普段Nuxt + microCMSで開発を行っており本モジュールの恩恵を受けています。
本モジュールを利用する上で以下2点を不安視しながら利用しています。

1. 本モジュールは今後もメンテされるのか
    - 半年以上mainブランチの更新がなく、こちらが1番大きい不安です
2. 本モジュールはNuxt Modulesとして追加されるのか
    - もし検討の余地があるのであれば私の方でNuxt公式側へPR提出致します。こちらはお任せ頂ければ対応致します。

今後メンテが継続されないのであればフォークしてメンテすることも視野に入れております。
お忙しいところ恐縮ですがお返事頂けると嬉しいです🙏

**Comment by dc7290** [comment]
ありがとうございます！！
社内で方針について確認を取りますのでもうしばらくお待ちいただけると・・・！

**Comment by shinGangan** [comment]
@dc7290 

コメントありがとうございます🙇
お手数おかけ致しますがよろしくお願い致します。

**Comment by dc7290** [comment]
お待たせしております🙇‍♂️

まず結論から先に申し上げますと、少なくとも現段階では明確な方針が決まっていないため、申し訳ないですがご不安があればフォークしていただけると幸いです。

その前提で、いただいている1と2に関してお答えさせていただきます。

1に関して

少なくとも積極的な機能追加はあまり考えていません。
ここでの「メンテ」はGanganさん的にはどういったものを示すものでしたでしょうか・・・？

2に関して

現時点ではNuxtModulesへの登録は考えていません。

**Comment by shinGangan** [comment]
お忙しい中ご回答頂きありがとうございます 🙇

こちらについて承知いたしました！ご回答頂きありがとうございます。

> まず結論から先に申し上げますと、少なくとも現段階では明確な方針が決まっていないため、申し訳ないですがご不安があればフォークしていただけると幸いです。

私の認識でのメンテは「Nuxtおよび関連ライブラリへの追従」を指しています。そのため、Nuxtおよび関連ライブラリのバージョンが上がっても正常に動作することを担保したいという意図です(担保に伴い一部リファクタリングが発生する可能性あり)

> 少なくとも積極的な機能追加はあまり考えていません。
ここでの「メンテ」はGanganさん的にはどういったものを示すものでしたでしょうか・・・？

こちらについても承知致しました。Nuxt(最新v3.10 or next v3.11)での動作確認が完了次第私の方で登録しようと思います。

> 現時点ではNuxtModulesへの登録は考えていません。

**Comment by dc7290** [comment]
> 私の認識でのメンテは「Nuxtおよび関連ライブラリへの追従」を指しています。そのため、Nuxtおよび関連ライブラリのバージョンが上がっても正常に動作することを担保したいという意図です(担保に伴い一部リファクタリングが発生する可能性あり)

なるほどですね。
明確な不具合が見つかった場合には修正が行われるかと思いますが、必ず追従していきます、という明言はちょっとできない状況ですね。。。

> こちらについても承知致しました。Nuxt(最新v3.10 or next v3.11)での動作確認が完了次第私の方で登録しようと思います。

ありがとうございます！

では、このIssueに関してはクローズさせていただきますが、またご不明点あればご連絡ください🙇‍♂️
